apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: app
  
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  sources:
  - repoURL: 'https://github.com/shukuchicoding/vdt_web-config.git'
    targetRevision: HEAD
    path: .
    helm: web-config
      valueFiles:
      - $values/values.yaml
  - repoURL: 'https://github.com/shukuchicoding/vdt-api-config.git'
    targetRevision: HEAD
    helm: api-config
      valueFiles:
      - $values/values.yaml
    path: .
